[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/phases"
  to = "/.netlify/functions/phases"
  status = 200

[[redirects]]
  from = "/api/reviews"
  to = "/.netlify/functions/reviews"
  status = 200

[[redirects]]
  from = "/api/submit-contact-form"
  to = "/.netlify/functions/submit-contact-form"
  status = 200

[[redirects]]
  from = "/api/case-studies"
  to = "/.netlify/functions/get-case-studies"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  framework = "vite"
